---

- name: restart ghost
  runit:
    name={{ ghost_service_name }} 
    action=restart
    state=up
    enabled=true
    timeout=9
  when: ghost_service_status is defined and not ghost_service_status.restarted

